- type: job
  id: HGuardsman
  name: job-name-guardsman
  description: job-description-guardsman
  playTimeTracker: JobHGuardsman
  startingGear: GuardsmanGear
  icon: "JobIconGuardsman"
  supervisors: job-supervisors-engineering
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Maintenance
  - Engineering
  - External
