- type: job
  id: HLieutenant
  name: job-name-lieutenant
  description: job-description-lieutenant
  playTimeTracker: JobHLieutenant
  startingGear: LieutenantGear
  icon: "JobIconLieutenant"
  supervisors: job-supervisors-engineering
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: LieutenantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    back: ClothingBackpackTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    neck: ClothingNeckRobeTechpriestMars
    id: PassengerPDA
