- type: job
  id: HSpecialistSWS
  name: job-name-specialist-sws
  description: job-description-specialist-sws
  playTimeTracker: JobHSpecialistSWS
  startingGear: GuardsmanGear
  icon: "JobIconSpecialistSWS"
  supervisors: job-supervisors-engineering
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Maintenance
  - Engineering
  - External
