- type: job
  id: SergeantHWS
  name: job-name-sergeant-hws
  description: job-description-sergeant-hws
  playTimeTracker: JobSergeantHWS
  startingGear: SergeantGear
  icon: "JobIconSergeantHWS"
  supervisors: job-supervisors-engineering
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Maintenance
  - Engineering
  - External
