- type: job
  id: TankComm
  name: job-name-tank-comm
  description: job-description-tank-comm
  playTimeTracker: JobTankComm
  startingGear: SergeantGear
  icon: "JobIconTankComm"
  supervisors: job-supervisors-engineering
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Maintenance
  - Engineering
  - External
