- type: department
  id: Mechanicus
  name: department-Mechanicus
  description: department-Mechanicus-description
  color: "#800000"
  roles:
  - Magos
  - Explorator
  - Lexmechanic
  - Genetor
  - Enginseer
  - Novice

- type: department
  id: Imperium
  name: department-Imperium
  description: department-Imperium-description
  color: "#006400"
  roles:
  - Colonel
  - Commissar
  - Lieutenant
  - TankComm
  - Tanker
  - Sergeant
  - SergeantSWS
  - SergeantHWS
  - SpecialistSWS
  - SpecialistHWS
  - Guardsman
  - Medic
  # - Passenger

- type: department
  id: DarkMechanicum
  name: department-Dark-Mechanicum
  description: department-Dark-Mechanicus-description
  color: "#800000"
  roles:
  - HMagos
  - HExplorator
  - HLexmechanic
  - HGenetor
  - HEnginseer
  - HNovice

- type: department
  id: Heretics
  name: department-Heretics
  description: department-Heretics-description
  color: "#800000"
  roles:
  - HColonel
  - HCommissar
  - HLieutenant
  - HTankComm
  - HTanker
  - HSergeant
  - HSergeantSWS
  - HSergeantHWS
  - HSpecialistSWS
  - HSpecialistHWS
  - HGuardsman
  - HMedic
